(global-set-key (kbd "C-<backspace>") 'fris/backward-kill-char-or-word)
(global-set-key (kbd "C-c n") 'fris/xah-new-empty-buffer)
(global-set-key (kbd "C-x k") 'fris/kill-this-buffer)
(global-set-key (kbd "C-S-k") 'fris/delete-window)
(global-set-key (kbd "M-a") 'fris/new-empty-buffer-in-window)
(global-set-key (kbd "M-r") 'rotate-window)
(global-set-key (kbd "M-k") 'fris/kill-buffer-and-window)
(global-set-key (kbd "M-p") 'backward-paragraph)
(global-set-key (kbd "M-n") 'forward-paragraph)
;(global-unset-key (kbd "M-{"))
;(global-unset-key (kbd "M-}"))

;(global-set-key (kbd "C-x C-S-f") 'fris/find-file-wsl)

(global-unset-key (kbd "<insertchar>"))
(global-unset-key (kbd "<insert>"))
(global-unset-key (kbd "C-d"))
(global-unset-key (kbd "C-S-d"))
(global-unset-key (kbd "C-x m"))

(global-unset-key (kbd "<mouse-movement>"))
(global-unset-key (kbd "<noname>"))
(global-unset-key (kbd "<rwindow>"))
(global-unset-key (kbd "<touch-end>"))
(global-unset-key (kbd "C-<noname>"))
(global-unset-key (kbd "C-M-<drag-mouse-1>"))
(global-unset-key (kbd "M-<noname>"))
(global-unset-key (kbd "<iconify-frame>"))
(global-unset-key (kbd "<language-change>"))
(global-unset-key (kbd "<lwindow>"))
(global-unset-key (kbd "<make-frame-visible>"))
(global-unset-key (kbd "C-@"))
(global-unset-key (kbd "C-x C-@"))
(global-unset-key (kbd "C-@"))
(global-unset-key (kbd "C-M-@"))
(global-unset-key (kbd "C-x r C-@"))
(global-unset-key (kbd "M-@"))
(global-unset-key (kbd "C-x @ S"))
(global-unset-key (kbd "C-x @ a"))
(global-unset-key (kbd "C-x @ c"))
(global-unset-key (kbd "C-x @ h"))
(global-unset-key (kbd "C-x @ m"))
(global-unset-key (kbd "C-x @ s"))
(global-unset-key (kbd "S-<mouse-4>"))
(global-unset-key (kbd "S-<mouse-5>"))
(global-unset-key (kbd "S-<mouse-6>"))
(global-unset-key (kbd "S-<mouse-7>"))
(global-unset-key (kbd "S-<wheel-down>"))
(global-unset-key (kbd "S-<wheel-left>"))
(global-unset-key (kbd "S-<wheel-right>"))
(global-unset-key (kbd "S-<wheel-up>"))
(global-unset-key (kbd "M-~"))
(global-unset-key (kbd "C-x v ~"))
(global-unset-key (kbd "<insert>"))
(global-unset-key (kbd "<insertchar>"))
(global-unset-key (kbd "C-<insert>"))
(global-unset-key (kbd "C-<insertchar>"))
(global-unset-key (kbd "C-M-."))
(global-unset-key (kbd "C-x 5 ."))
(global-unset-key (kbd "M-,"))
(global-unset-key (kbd "M-."))
(global-unset-key (kbd "M-?"))
(global-unset-key (kbd "C-x 4 ."))
(global-unset-key (kbd "C-M-,"))
(global-unset-key (kbd "C-d"))
(global-unset-key (kbd "<XF86Back>"))
(global-unset-key (kbd "<XF86Forward>"))
(global-unset-key (kbd "<again>"))
(global-unset-key (kbd "<begin>"))
(global-unset-key (kbd "<compose-last-chars>"))
(global-unset-key (kbd "<copy>"))
(global-unset-key (kbd "<cut>"))
(global-unset-key (kbd "<delete-frame>"))
(global-unset-key (kbd "<execute>"))
(global-unset-key (kbd "<f10>"))
(global-unset-key (kbd "<f16>"))
(global-unset-key (kbd "<f18>"))
(global-unset-key (kbd "<f20>"))
(global-unset-key (kbd "C-x ("))
(global-unset-key (kbd "C-x )"))
(global-unset-key (kbd "C-x *"))
(global-unset-key (kbd "C-x 5 0"))
(global-unset-key (kbd "C-x 5 1"))
(global-unset-key (kbd "C-x 5 2"))
(global-unset-key (kbd "C-x 5 5"))
(global-unset-key (kbd "C-x 5 C-f"))
(global-unset-key (kbd "C-x 5 C-o"))
(global-unset-key (kbd "C-x 5 b"))
(global-unset-key (kbd "C-x 5 c"))
(global-unset-key (kbd "C-x 5 d"))
(global-unset-key (kbd "C-x 5 f"))
(global-unset-key (kbd "C-x 5 m"))
(global-unset-key (kbd "C-x 5 o"))
(global-unset-key (kbd "C-x 5 p"))
(global-unset-key (kbd "C-x 5 r"))
(global-unset-key (kbd "C-x 5 u"))
(global-unset-key (kbd "C-x 8 e +"))
(global-unset-key (kbd "C-x 8 e -"))
(global-unset-key (kbd "C-x 8 e 0"))
(global-unset-key (kbd "C-x 8 e d"))
(global-unset-key (kbd "C-x 8 e e"))
(global-unset-key (kbd "C-x 8 e i"))
(global-unset-key (kbd "C-x 8 e l"))
(global-unset-key (kbd "C-x 8 e r"))
(global-unset-key (kbd "C-x 8 e s"))
(global-unset-key (kbd "C-x ="))
(global-unset-key (kbd "C-x C-<left>"))
(global-unset-key (kbd "C-x C-<right>"))
(global-unset-key (kbd "C-x C-z"))
(global-unset-key (kbd "C-x ESC ESC"))
(global-unset-key (kbd "C-x M-:"))
(global-unset-key (kbd "C-x RET F"))
(global-unset-key (kbd "C-x RET X"))
(global-unset-key (kbd "C-x RET c"))
(global-unset-key (kbd "C-x RET f"))
(global-unset-key (kbd "C-x RET k"))
(global-unset-key (kbd "C-x RET l"))
(global-unset-key (kbd "C-x RET p"))
(global-unset-key (kbd "C-x RET r"))
(global-unset-key (kbd "C-x RET t"))
(global-unset-key (kbd "C-x RET x"))
(global-unset-key (kbd "ESC <begin>"))
(global-unset-key (kbd "ESC <end>"))
(global-unset-key (kbd "ESC <f10>"))
(global-unset-key (kbd "ESC <home>"))
(global-unset-key (kbd "ESC <left>"))
(global-unset-key (kbd "ESC <next>"))
(global-unset-key (kbd "ESC <prior>"))
(global-unset-key (kbd "ESC <right>"))
(global-unset-key (kbd "ESC C-<backspace>"))
(global-unset-key (kbd "ESC C-<delete>"))
(global-unset-key (kbd "ESC C-<down>"))
(global-unset-key (kbd "ESC C-<end>"))
(global-unset-key (kbd "ESC C-<home>"))
(global-unset-key (kbd "ESC C-<left>"))
(global-unset-key (kbd "ESC C-<right>"))
(global-unset-key (kbd "ESC C-<up>"))
(global-unset-key (kbd "C-t"))
(global-unset-key (kbd "M-("))
