(deftheme tsoding
  "Edited tsoding's gruber-darker by cofeek-codes")

(custom-theme-set-variables
 'tsoding
 '(frame-brackground-mode 'dark))

(custom-theme-set-faces
 'tsoding
 '(font-latex-bold-face ((t (:foreground "#95a99f" :bold t))))
 '(font-latex-italic-face ((t (:foreground "#95a99f" :italic t))))
 '(font-latex-math-face ((t (:foreground "#73c936"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#96a6c8" :bold t))))
 '(font-latex-slide-title-face ((t (:foreground "#96a6c8"))))
 '(font-latex-string-face ((t (:foreground "#73c936"))))
 '(font-latex-warning-face ((t (:foreground "tomato"))))
 '(border ((t (:background "#101010" :foreground "#453d41"))))
 '(cursor ((t (:background "#ffdd33"))))
 '(fringe ((t (:background nil :foreground "#453d41"))))
 '(vertical-border ((t (:foreground "#453d41"))))
 '(link ((t (:foreground "#96a6c8" :underline t))))
 '(link-visited ((t (:foreground "#9e95c7" :underline t))))
 '(match ((t (:background "#52494e"))))
 '(shadow ((t (:foreground "#52494e"))))
 '(minibuffer-prompt ((t (:foreground "#96a6c8"))))
 '(region ((t (:background "#484848" :foreground nil))))
 '(secondary-selection ((t (:background "#484848" :foreground nil))))
 '(trailing-whitespace ((t (:foreground "#000000" :background "#f43841"))))
 '(tooltip ((t (:background "#52494e" :foreground "#ffffff"))))
 '(holiday-face ((t (:foreground "#f43841"))))
 '(compilation-info ((t (:foreground "#73c936" :inherit unspecified))))
 '(compilation-warning ((t (:foreground "#cc8c3c" :bold t :inherit unspecified))))
 '(compilation-error ((t (:foreground "#ff4f58"))))
 '(compilation-mode-line-fail ((t (:foreground "#f43841" :weight bold :inherit unspecified))))
 '(compilation-mode-line-exit ((t (:foreground "#73c936" :weight bold :inherit unspecified))))
 '(completions-annotations ((t (:inherit 'shadow))))
 '(custom-state ((t (:foreground "#73c936"))))
 '(diff-removed ((t (:foreground "#ff4f58" :background nil))))
 '(diff-added ((t (:foreground "#73c936" :background nil))))
 '(dired-directory ((t (:foreground "#96a6c8" :weight bold))))
 '(dired-ignored ((t (:foreground "#95a99f" :inherit unspecified))))
 '(ebrowse-root-class ((t (:foreground "#96a6c8" :weight bold))))
 '(ebrowse-progress ((t (:background "#96a6c8"))))
 '(erc-notice-face ((t (:foreground "#9e95c7"))))
 '(erc-timestamp-face ((t (:foreground "#73c936"))))
 '(erc-input-face ((t (:foreground "#ff4f58"))))
 '(erc-my-nick-face ((t (:foreground "#ff4f58"))))
 '(eshell-ls-backup ((t (:foreground "#95a99f"))))
 '(eshell-ls-directory ((t (:foreground "#96a6c8"))))
 '(eshell-ls-executable ((t (:foreground "#73c936"))))
 '(eshell-ls-symlink ((t (:foreground "#ffdd33"))))
 '(font-lock-builtin-face ((t (:foreground "#ffdd33"))))
 '(font-lock-comment-face ((t (:foreground "#cc8c3c"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#cc8c3c"))))
 '(font-lock-constant-face ((t (:foreground "#95a99f"))))
 '(font-lock-doc-face ((t (:foreground "#73c936"))))
 '(font-lock-doc-string-face ((t (:foreground "#73c936"))))
 '(font-lock-function-name-face ((t (:foreground "#96a6c8"))))
 '(font-lock-keyword-face ((t (:foreground "#ffdd33" :bold t))))
 '(font-lock-preprocessor-face ((t (:foreground "#95a99f"))))
 '(font-lock-reference-face ((t (:foreground "#95a99f"))))
 '(font-lock-string-face ((t (:foreground "#73c936"))))
 '(font-lock-type-face ((t (:foreground "#95a99f"))))
 '(font-lock-variable-name-face ((t (:foreground "#f4f4ff"))))
 '(font-lock-warning-face ((t (:foreground "#f43841"))))
 '(flymake-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#f43841") :foreground unspecified :background unspecified :inherit unspecified)) (t (:foreground "#f43841" :weight bold :underline t))))
 '(flymake-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#ffdd33") :foreground unspecified :background unspecified :inherit unspecified)) (t (:forground "#ffdd33" :weight bold :underline t))))
 '(flymake-infoline ((((supports :underline (:style wave))) (:underline (:style wave :color "#73c936") :foreground unspecified :background unspecified :inherit unspecified)) (t (:forground "#73c936" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#f43841") :inherit unspecified)) (t (:foreground "#f43841" :weight bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#ffdd33") :inherit unspecified)) (t (:foreground "#ffdd33" :weight bold :underline t))))
 '(ido-first-match ((t (:foreground "#ffdd33" :bold nil))))
 '(ido-only-match ((t (:foreground "#cc8c3c" :weight bold))))
 '(ido-subdir ((t (:foreground "#96a6c8" :weight bold))))
 '(info-xref ((t (:foreground "#96a6c8"))))
 '(info-visited ((t (:foreground "#9e95c7"))))
 '(highlight ((t (:background "#282828" :foreground nil))))
 '(highlight-current-line-face ((t (:background "#282828" :foreground nil))))
 '(line-number ((t (:inherit default :foreground "#52494e"))))
 '(line-number-current-line ((t (:inherit line-number :foreground "#ffdd33"))))
 '(linum ((t `(list :foreground gruber-darker-quartz :background gruber-darker-bg))))
 '(magit-branch ((t (:foreground "#96a6c8"))))
 '(magit-diff-hunk-header ((t (:background "#453d41"))))
 '(magit-diff-file-header ((t (:background "#52494e"))))
 '(magit-log-sha1 ((t (:foreground "#ff4f58"))))
 '(magit-log-author ((t (:foreground "#cc8c3c"))))
 '(magit-log-head-label-remote ((t (:foreground "#73c936" :background "#282828"))))
 '(magit-log-head-label-local ((t (:foreground "#96a6c8" :background "#282828"))))
 '(magit-log-head-label-tags ((t (:foreground "#ffdd33" :background "#282828"))))
 '(magit-log-head-label-head ((t (:foreground "#e4e4ef" :background "#282828"))))
 '(magit-item-highlight ((t (:background "#282828"))))
 '(magit-tag ((t (:foreground "#ffdd33" :background "#181818"))))
 '(magit-blame-heading ((t (:background "#282828" :foreground "#e4e4ef"))))
 '(message-header-name ((t (:foreground "#73c936"))))
 '(mode-line ((t (:background "#282828" :foreground "#ffffff"))))
 '(mode-line-buffer-id ((t (:background "#282828" :foreground "#ffffff"))))
 '(mode-line-inactive ((t (:background "#282828" :foreground "#95a99f"))))
 '(neo-dir-link-face ((t (:foreground "#96a6c8"))))
 '(org-agenda-structure ((t (:foreground "#96a6c8"))))
 '(org-column ((t (:background "#101010"))))
 '(org-column-title ((t (:background "#101010" :underline t :weight bold))))
 '(org-done ((t (:foreground "#73c936"))))
 '(org-todo ((t (:foreground "#c73c3f"))))
 '(org-upcoming-deadline ((t (:foreground "#ffdd33"))))
 '(isearch ((t (:foreground "#000000" :background "#f5f5f5"))))
 '(isearch-fail ((t (:foreground "#000000" :background "#f43841"))))
 '(isearch-lazy-highlight-face ((t (:foreground "#f4f4ff" :background "#565f73"))))
 '(sh-quoted-exec ((t (:foreground "#ff4f58"))))
 '(show-paren-match-face ((t (:background "#52494e"))))
 '(show-paren-mismatch-face ((t (:background "#c73c3f"))))
 '(slime-repl-inputed-output-face ((t (:foreground "#f43841"))))
 '(tuareg-font-lock-governing-face ((t (:foreground "#ffdd33"))))
 '(speedbar-directory-face ((t (:foreground "#96a6c8" :weight bold))))
 '(speedbar-file-face ((t (:foreground "#e4e4ef"))))
 '(speedbar-highlight-face ((t (:background "#282828"))))
 '(speedbar-selected-face ((t (:foreground "#f43841"))))
 '(speedbar-tag-face ((t (:foreground "#ffdd33"))))
 '(which-func ((t (:foreground "#9e95c7"))))
 '(whitespace-space ((t (:background "#181818" :foreground "#282828"))))
 '(whitespace-tab ((t (:background "#181818" :foreground "#282828"))))
 '(whitespace-hspace ((t (:background "#181818" :foreground "#453d41"))))
 '(whitespace-line ((t (:background "#453d41" :foreground "#ff4f58"))))
 '(whitespace-newline ((t (:background "#181818" :foreground "#453d41"))))
 '(whitespace-trailing ((t (:background "#f43841" :foreground "#f43841"))))
 '(whitespace-empty ((t (:background "#ffdd33" :foreground "#ffdd33"))))
 '(whitespace-indentation ((t (:background "#ffdd33" :foreground "#f43841"))))
 '(whitespace-space-after-tab ((t (:background "#ffdd33" :foreground "#ffdd33"))))
 '(whitespace-space-before-tab ((t (:background "#cc8c3c" :foreground "#cc8c3c"))))
 '(tab-bar ((t (:background "#282828" :foreground "#52494e"))))
 '(tab-bar-tab ((t (:background nil :foreground "#ffdd33" :weight bold))))
 '(tab-bar-tab-inactive ((t (:background nil))))
 '(term-color-black ((t (:foreground "#484848" :background "#52494e"))))
 '(term-color-red ((t (:foreground "#c73c3f" :background "#c73c3f"))))
 '(term-color-green ((t (:foreground "#73c936" :background "#73c936"))))
 '(term-color-blue ((t (:foreground "#96a6c8" :background "#96a6c8"))))
 '(term-color-yellow ((t (:foreground "#ffdd33" :background "#ffdd33"))))
 '(term-color-magenta ((t (:foreground "#9e95c7" :background "#9e95c7"))))
 '(term-color-cyan ((t (:foreground "#95a99f" :background "#95a99f"))))
 '(term-color-white ((t (:foreground "#e4e4ef" :background "#ffffff"))))
 '(company-tooltip ((t (:foreground "#e4e4ef" :background "#282828"))))
 '(company-tooltip-annotation ((t (:foreground "#cc8c3c" :background "#282828"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#cc8c3c" :background "#101010"))))
 '(company-tooltip-selection ((t (:foreground "#e4e4ef" :background "#101010"))))
 '(company-tooltip-mouse ((t (:background "#101010"))))
 '(company-tooltip-common ((t (:foreground "#73c936"))))
 '(company-tooltip-common-selection ((t (:foreground "#73c936"))))
 '(company-tooltip-scrollbar-thumb ((t (:background "#101010"))))
 '(company-tooltip-scrollbar-track ((t (:background "#453d41"))))
 '(company-preview ((t (:background "#73c936"))))
 '(company-preview-common ((t (:foreground "#73c936" :background "#101010"))))
 '(proof-locked-face ((t (:background "#303540"))))
 '(orderless-match-face-0 ((t (:foreground "#ffdd33"))))
 '(orderless-match-face-1 ((t (:foreground "#73c936"))))
 '(orderless-match-face-2 ((t (:foreground "#cc8c3c"))))
 '(orderless-match-face-3 ((t (:foreground "#95a99f"))))
 '(rust-unsafe ((t (:inherit font-lock-keyword-face))))
 '(default ((t (:foreground "#e4e4ef" :background "#181818"))))
 '(font-latex-script-char-face ((t (:inherit font-latex-warning-face)))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'tsoding)
