#!/bin/sh

# autostart
$HOME/.local/bin/autostart.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a st_float state=floating
